name: expense_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  dartz: ^0.10.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0  # For internationalization and message formatting
  fl_chart: ^0.70.0  # For beautiful charts
  flutter_local_notifications: ^19.4.0  # For local notifications (using the latest stable version)
  timezone: ^0.10.0  # For timezone support in notifications (updated for compatibility with flutter_local_notifications 19.4.0)
  permission_handler: ^11.3.0  # For handling permissions
  smooth_page_indicator: ^1.1.0  # For page indicators in onboarding
  flutter_svg: ^2.0.10  # For rendering SVG images
  cupertino_icons: ^1.0.8
  go_router: ^13.2.0  # For declarative routing
  flutter_native_splash: ^2.4.6
  logger: ^2.0.2  # For logging
  flutter_bloc: ^8.1.4  # For state management with BLoC pattern
  bloc: ^8.1.2  # Core BLoC library

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.2  # For generating localization files
  mocktail: ^1.0.3  # For mocking in tests
  bloc_test: ^9.1.4  # For testing BLoCs
  test: ^1.24.0  # Core test package

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # Enable code generation for localization
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets management
  assets:
    - assets/svg/
    - assets/fonts/
    - assets/data/currencies.json
    - assets/flags/
    
  # Fonts configuration
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700

# Splash screen configuration
flutter_native_splash:
  # Background color (will be used as fallback if gradient is not supported)
  color: "#283339"
  # Set splash image
  image: "assets/svg/splash.svg"
  # Platform specific settings
  android: true
  ios: true
  web: false
  # Background image with gradient (will be handled in Flutter code)
  background_image: "assets/images/splash_background.png"
  # Center the logo
  android_gravity: center
  ios_content_mode: center

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
