// Mocks generated by Mockito 5.4.6 from annotations
// in expense_app/test/features/currency/domain/usecases/get_all_currencies_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:expense_app/features/currency/domain/entities/currency.dart'
    as _i4;
import 'package:expense_app/features/currency/domain/repositories/currency_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CurrencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyRepository extends _i1.Mock
    implements _i2.CurrencyRepository {
  MockCurrencyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Currency>> getAllCurrencies() => (super.noSuchMethod(
        Invocation.method(
          #getAllCurrencies,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Currency>>.value(<_i4.Currency>[]),
      ) as _i3.Future<List<_i4.Currency>>);

  @override
  _i3.Future<List<_i4.Currency>> searchCurrencies(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCurrencies,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.Currency>>.value(<_i4.Currency>[]),
      ) as _i3.Future<List<_i4.Currency>>);

  @override
  _i3.Future<void> setSelectedCurrency(_i4.Currency? currency) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSelectedCurrency,
          [currency],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
