name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Flutter Lint & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.2'  # Match local Flutter version
          
      - name: Run Flutter doctor
        run: flutter doctor -v

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses
        
      - name: Get Flutter dependencies
        run: flutter pub get
        
      - name: Show versions
        run: |
          flutter --version
          dart --version
          
      - name: Run Flutter analyze
        run: flutter analyze --fatal-infos --fatal-warnings
        
      - name: Run Dart format check
        run: dart format --set-exit-if-changed .
        
      - name: Run Flutter test
        run: flutter test --coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          fail_ci_if_error: false
